#dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb
#dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
#dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb

dtb-$(CONFIG_ARCH_SDM670) += sirius-sdm710.dtb \
	sirius-sdm670.dtb

dtb-$(CONFIG_ARCH_MSM8953) += msm8953-cdp.dtb \
	msm8953-mtp.dtb \
	msm8953-ext-codec-mtp.dtb \
	msm8953-qrd-sku3.dtb \
	msm8953-rcm.dtb \
	apq8053-rcm.dtb \
	msm8953-ext-codec-rcm.dtb \
	apq8053-cdp.dtb \
	apq8053-ipc.dtb \
	msm8953-ipc.dtb \
	apq8053-mtp.dtb \
	apq8053-ext-audio-mtp.dtb \
	apq8053-ext-codec-rcm.dtb \
	msm8953-cdp-1200p.dtb \
	msm8953-iot-mtp.dtb \
	apq8053-iot-mtp.dtb \
	apq8053-lite-dragon-v1.0.dtb \
	apq8053-lite-dragon-v2.0.dtb \
	apq8053-lite-dragon-v2.1.dtb \
	apq8053-lite-dragon-v2.2.dtb \
	apq8053-lite-dragon-v2.2.1.dtb \
	apq8053-lite-dragon-v2.3.dtb \
	apq8053-lite-dragon-v2.4.dtb \
	apq8053-lat-concam-dev.dtb \
	apq8053-lat-concam-proto.dtb \
	msm8953-pmi8940-cdp.dtb \
	msm8953-pmi8940-mtp.dtb \
	msm8953-pmi8937-cdp.dtb \
	msm8953-pmi8937-mtp.dtb \
	msm8953-pmi8940-ext-codec-mtp.dtb \
	msm8953-pmi8937-ext-codec-mtp.dtb \
	msm8953-pmi632-cdp-s2.dtb

dtb-$(CONFIG_ARCH_MSM8937) += msm8937-pmi8950-mtp.dtb \
	msm8937-interposer-sdm439-cdp.dtb \
	msm8937-interposer-sdm439-mtp.dtb \
	msm8937-interposer-sdm439-qrd.dtb \
	msm8937-interposer-sdm429-cdp.dtb \
	msm8937-interposer-sdm429-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8940) += msm8940-pmi8937-mtp.dtb \
	msm8940-pmi8950-mtp.dtb \
	msm8940-pmi8940-mtp.dtb

dtb-$(CONFIG_ARCH_MSM8917) += msm8917-pmi8950-mtp.dtb \
	msm8917-pmi8950-cdp.dtb \
	msm8917-pmi8950-rcm.dtb \
	msm8917-pmi8950-ext-codec-cdp.dtb \
	msm8917-pmi8950-cdp-mirror-lake-touch.dtb \
	apq8017-pmi8950-cdp-wcd-rome.dtb \
	apq8017-pmi8950-mtp.dtb \
	apq8017-pmi8950-cdp.dtb \
	msm8917-pmi8937-qrd-sku5.dtb \
	msm8917-pmi8937-mtp.dtb \
	msm8917-pmi8937-cdp.dtb \
	msm8917-pmi8937-rcm.dtb \
	apq8017-pmi8937-mtp.dtb \
	apq8017-pmi8937-cdp.dtb \
	apq8017-pmi8937-cdp-wcd-rome.dtb \
	msm8917-pmi8940-mtp.dtb \
	msm8917-pmi8940-cdp.dtb \
	msm8917-pmi8940-rcm.dtb

dtb-$(CONFIG_ARCH_QM215) += qm215-qrd.dtb

dtb-$(CONFIG_ARCH_MSM8909) += sdw3100-msm8909w-wtp.dtb \
	sdw3100-apq8009w-wtp.dtb \
	sdw3100-apq8009w-alpha.dtb \
	apq8009-mtp-wcd9326-refboard.dtb \
	apq8009-robot-som-refboard.dtb \
	apq8009-robot-rome-refboard.dtb \
	apq8009-robot-pronto-refboard.dtb \
	apq8009-dragon.dtb \
	apq8009-lat-v1.0.dtb \
	sdw3100-msm8909w-1gb-wtp.dtb

dtb-$(CONFIG_ARCH_SDM450) += sdm450-rcm.dtb \
	sdm450-cdp.dtb \
	sdm450-mtp.dtb \
	sda450-cdp.dtb \
	sda450-mtp.dtb \
	sdm450-qrd.dtb \
	sdm450-pmi8940-mtp.dtb \
	sdm450-pmi8937-mtp.dtb \
	sdm450-iot-mtp.dtb \
	sdm450-qrd-sku4.dtb \
	sdm450-pmi632-cdp-s2.dtb \
	sdm450-pmi632-mtp-s3.dtb \
	sda450-pmi632-cdp-s2.dtb \
	sda450-pmi632-mtp-s3.dtb

dtb-$(CONFIG_ARCH_SDM632) += sdm632-rumi.dtb \
	sdm632-cdp-s2.dtb \
	sdm632-ext-codec-cdp-s3.dtb \
	sdm632-mtp-s3.dtb \
	sdm632-ext-codec-mtp-s4.dtb \
	sdm632-rcm.dtb \
	sdm632-qrd-sku4.dtb \
	sdm632-qrd.dtb \
	sdm632-pm8004-cdp-s2.dtb \
	sdm632-pm8004-ext-codec-cdp-s3.dtb \
	sdm632-pm8004-mtp-s3.dtb \
	sdm632-pm8004-ext-codec-mtp-s4.dtb \
	sdm632-pm8004-rcm.dtb \
	sdm632-pm8004-qrd-sku4.dtb \
	sdm632-pm8004-qrd.dtb

dtb-$(CONFIG_ARCH_SDM439) += sdm439-mtp.dtb \
	sdm439-cdp.dtb \
	sdm439-qrd.dtb \
	sda439-mtp.dtb \
	sda439-cdp.dtb \
	sdm439-external-codec-mtp.dtb \
	sdm439-rcm.dtb \
	qm215-qrd.dtb

dtb-$(CONFIG_ARCH_SDM429) += sdm429-mtp.dtb \
	sdm429-cdp.dtb \
	sdm429-qrd.dtb \
	sda429-mtp.dtb \
	sda429-cdp.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
